apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fnwx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0096-tenant/ci1t-830-0096-app/devfile-sample-fnwx@sha256:2b31fd8d85297a608f05991650f61693dc8dc563946294c15308e13e0eb01eec
        name: my-nodejs
        resources: {}
status: {}
