apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-fnwx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-fnwx
    app.kubernetes.io/part-of: ci1t-830-0096-app
  name: devfile-sample-fnwx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-fnwx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-fnwx
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0096-tenant/ci1t-830-0096-app/devfile-sample-fnwx@sha256:2b31fd8d85297a608f05991650f61693dc8dc563946294c15308e13e0eb01eec
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
